spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/datajpa
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  # 글로벌 페이징 설정
  data:
    web:
      pageable:
        default-page-size: 10 # 기본 페이지 사이즈
        max-page-size: 1000 # 최대 페이지 사이즈
        one-indexed-parameters: true # 페이지 1부터 시작

logging.level:
  org.hibernate.SQL: debug
